language: go
go:
- '1.12.x'
script:
- make get
- make test
- go build -o $TRAVIS_BUILD_DIR/bin/tokeninfo
- mv $TRAVIS_BUILD_DIR/scripts/ $TRAVIS_BUILD_DIR/bin/
- mv $TRAVIS_BUILD_DIR/codedeploy/* $TRAVIS_BUILD_DIR/bin/
- cd $TRAVIS_BUILD_DIR/bin
- zip -r $TRAVIS_COMMIT *
- mkdir -p dsource
- mv $TRAVIS_COMMIT.zip dsource/$TRAVIS_COMMIT.zip
deploy:
- provider: s3
  access_key_id: "$AWS_ACCESS_KEY"
  secret_access_key: "$AWS_SECRET_KEY"
  bucket: "$AWS_S3_BUCKET"
  region: "$AWS_REGION"
  skip_cleanup: true
  local_dir: dsource
  upload-dir: tokeninfo
- provider: codedeploy
  access_key_id: "$AWS_ACCESS_KEY"
  secret_access_key: "$AWS_SECRET_KEY"
  bucket: "$AWS_S3_BUCKET"
  region: "$AWS_REGION"
  key: tokeninfo/$TRAVIS_COMMIT.zip
  bundle: zip
  application: tokeninfo-dev-app
  deployment_group: tokeninfo-dev-deployment-group
env:
  global:
  - secure: aIWN6VCCK/qv7rPn6TV/QRmUL6Pv3oA3KipwhnCpqE9Y+fdNcYjJdKU5J/dAgWEykmxaNtOhQnHXe0bME/dGBvP78xJCynA3VhnmahfvIPyq5a9xSM4N30WcJfkMZ9OEPIxgxUKKPZB+vskny81bfQvcN9Ge+e+vB5ij97hwkiB/pcGSiMwT5UCm4vdNdndYUGo3xSaBkJva4AUu3WOSmXagVAUVbaJnWRrFGJFpcAZnlDoHiJcBVCDcpTQDGG6jJ8sVGbVEcsgY4Kzw73uZ9LJeR8XnqjGK0Jizzqw5m+C6OhQVyg7oa73QVxIkVmQW9srmqOv3ZguGQ/VeQY9s2OVO+1uJTx5l3tzlUR9B+4UitQ0ht7cwFMysrGKkK0qtlR/Jk7V0gis6nPPkbiWR3cxNEm+2IhqCMZ7vbrI2+hTKh0r4BN/37+gwwI3/QlcCg42ja9ljVFa6qtvlWLJohKyJ6LQgCiZejqs86PyzvBcjBQLnfhaL+BNcuXpD40x2Oebj3gxW5zxd4/LBmCU2ki9IQQiC71vM3yPWTfCESLnYyBpjlSlmXGKElg5wd/z+IxqYk9ahYS9jK/KR7sFPwTTpx1cE8gGZh0VmWX24OTUnv6L6yqg1PsCdnPhgQQcnzLCNHiRi/L++JjhaGDPJjuWQPZlHc9NSt6+l7zEtTdU=
  - secure: XCZJdCQ0W6TPds/rwVeswEe4H2iv9hUgrIDiVYMESLGuOPGRjBcJ2SQCUGwSvm9+YTscLhU3yrlTJy5eYOWKqYzqgOydUkgm5VusT46v7mNiA1R+BQ/fCByzqCzV2ASfdsaeND/qQGfP+EUAVzSKMLzbb9q881nQrwHUA0EB8LYoqCALUS446ULypateB+s5kLT3wikA9FB3eRgC6IURfWHiU4J0yHjgrjnVy+ioaHFrZob9zUB6/tlgH96Y9R/hTCWHXUaetR4bDtGSKS/ZoF+lf0i3g+i9KFW/U0rBQlVMir8BQ8qtJmoqqHvB0FXzNk34cRw3aMbZt9gaNizvgYPi0MwcGt9B6Nv37pAIMtwDM7XTwGG0C/VKjCdDmqNxjuviAj3dRhZLxnDz2GB1x9cp8faeiViv2gsbh7W2ZtoqOcuUOs0K+/sctP0jGpWLg/U+tfkoaRbpHpSyEq877Nj1ij8oM2DFsCpnBlkeJyHkNzlhb4DaDNna2GaVu+rrs/1uvFv9ft+8FHcbpg7cjE2f4Oi8+VOhf7yVflb/71M2CC3a8HTrNSfxgpaeS67RxdHC3sGh5wHCYaIENF+PJb8z9szcNJBXMWxb0u9RSYLJevyeodmoiLhkMDY81ZmFHcsBAkLVAqbU9aCJeFA/uiju2+kATmoZvx/+bW6FTsg=
  - secure: omv/25j2eqMqMTkZC6QbSOedpTmpOJRsEDOgMcblk4s4cNsetmDau2ZDwX8xhzDIFjab5ZAEtZCoDXcm/ZK6enIweVMm0DxahuXYDxrJ5KJABOTFphccB8va8zkwADS3hQHBVQ2qmfIEp9lUOVKGf+uHTcy5sZmvgl9NG+7anbO521Lux5GICNPGyPhhgSM8L48RCrTuarq5S+4YP3erJ3Fp8vWrLtBdJ/31ZpQfc5uYu1MnYsjVZ/7wEp1+lntukXeO4fHdHho23DHaDL9mYxp6Cn94Cc0naUWRE5P65lmh/xNw9MjncfzA2mGcYq10M/wNMjXt7JnN9oyCf/iNLzJLdf/ypCpagCd/lMFkc/dij1/tE2Y/yYC8Hw4FTPaUq2w0vbQByQ/RGtmB0l4cIJ9dzBLy6yfn/X+bLr916TxOziR3xU1CJWvLJIJAa94zD0Nov7mDZ/fmTF7fqz9OelYsrMkBPQsH93QOM+ECuE0EkeBo4GZ1BWt4xfNF7wxxBh88/iiduVd5jhMLJ9I2xO+AONcvkf3mcWXBei8CJm+vhZwbGp0eMJinpM21wG3PG8NCQ23rqSpckOuosQ5FEs7xBA9XgEy8cL4o2Z+lnxLFfCjKgGISlE3ke3fBS2StvpwB5LkMjTWqXX6Nauw7tmxNH/pRltZdb+TCQ6S8xQI=
  - secure: CdYy0XxoL37HnxTOlXxfiSWgzKu4/cEIKcb7Q10ardBwJD7ZCs6GX+0r437CNAlSxLManelX8LrPAU1inQE84HbEVzI1FlZtCG1RNdJO/kcapQcJABT7Ry+7LVZF7ZeRXf401pzenxFetDNW0j8kVaXlRHQjLZO10ked7BUy7ffXE6LB/f6Q6QodvzdHnEstivPEjGD40Yk8PGwMVpotZvYfpcSfIWUC5BBH5gJLWtVJi/y0SdYWuQgeARPoxzGpYjQRHR8Mg7v18q/ErYohe/ehAdX/6r6+qHh6jYdLmPjT0R8LbL/mb1UoVG+BniwVgciXxkrKyUpYZHMeocY+OJBYc189FPcMH/dlalac18ckjxIjhlU5PJxBt+ktsD+iGa4bimIUOzLi+fAlM3KNOxYePZ7XZHCtsfg+f8SGR5TTn36J6ymtMrFe65HlTBHMXCLdLOlgp3JDRXqpdrpzNIKjHAeAytYe+85RK/Ni9THU+dZBgXL2KeJ3VBXK33u7fP1QRyrWeBRD0qtDogRYsrMy5y9+c3kpSc1UPWTcWSaiX+e8RG/b5xqLOOTchNUc6SkelYNLUgcPv+owbiapXE0JPFVZz+miCeHVzp1dkeByKnxmWI0/nmwTiwVt8d4MHb/Jdv6SmhJB5Hs1MpIfoDPtr4vNx+msDI7cSfog5FA=
  matrix:
  - GO111MODULE=on
