language: go
go:
  - "1.10"

script:
  - go build -o $TRAVIS_BUILD_DIR/bin/tokeninfo
  - mv $TRAVIS_BUILD_DIR/scripts/ $TRAVIS_BUILD_DIR/bin/
  - mv $TRAVIS_BUILD_DIR/codedeploy/* $TRAVIS_BUILD_DIR/bin/
  - cd $TRAVIS_BUILD_DIR/bin
  - zip -r latest *
  - mkdir -p dsource
  - mv latest.zip dsource/latest.zip

deploy:
- provider: s3
  access_key_id: $AWS_ACCESS_KEY
  secret_access_key: $AWS_SECRET_KEY
  bucket: $S3_BUCKET
  region: $AWS_REGION
  skip_cleanup: true
  local_dir: dsource
  upload-dir: tokeninfo
- provider: codedeploy
  access_key_id: $AWS_ACCESS_KEY
  secret_access_key: $AWS_SECRET_KEY
  bucket: $S3_BUCKET
  region: $AWS_REGION
  key: tokeninfo/latest.zip
  bundle: zip
  application: tokeninfo-dev-app
  deployment_group: tokeninfo-dev-deployment-group
env:
  global:
  - secure: Gj7K2/4MMz2sGUUFx/S05l0a0ZWnIL05fPpHOWB08JXjUInhL+QHTIgxV442pXY5IJYlZzVuE4GRNCe6w3ssM+hAB3kYwYespCojVNZPPzTwynXRpRlHi39NifJ9L9JSzfdm4zFECbgFHz/Nw3AmrWPq/TOe90RLp63gM5dU5XkhrWoqS5cYYf1Y7869VEx0D6pqF8KyYGR1ssdEmtcqnjhwNzamA87MLO6a+8+3BTOE2mk93F3lZ0fGtiLNb6dUNEnfKqmuilGnzJkVImRJEZPj9hU0lX5bABueFryYJg5m3y3hMlO9Ox/Xxp4n0HGkR9RNQDFKtq8b9p6zThJ3mlE4tSY+rsOHh7v8xRLD3RbSYVeVwRFA1bqgdxNhuqted6sRUKmFuJfr2N9itjhbLLbPAAjNR1H9FQfXGQSNAdbH+5IADTZ4dLhlbthP/t6k7ptX34rdwVrUrIMy+R27ekyRNJN53XRkbE9TcC28hnOYO31jYdm7bnzJwXAZAF1XTJGgKlSwLCmc/ngxV/RaLa/eGpV3ZDdysh0R56tRcq6BUIpNTkvpHIZ4s6RpQ3YvZb/s/mYKiLeAlqRxUJUfWO8sFQYucUfNmMGZVInEFcIo1vwqcLWijqIGRBqo5riTOp8Asq6FKw3HZdAZQOkL40KK7wLi0rPp66dV7gQk9Nw=
  - secure: ag+r6n7cuVRoi5fTco51b9isXeTjEeIwXKsyCmkh45a+e7r+6gA6846m5294sjkutmmq3v+7X4mi07K2cJY1XC8g6TmbYbjAmOs5LcXJu1Rk9YKT/gKNs6IGaHQwaBjAQa6pipOmjDy8KWcZM6IHuF1AxK5iljdKljILnRfkK11drI+iXcdeqmmI42aLXfehOtRsYMjbO3zQB8qhyTsegOiXPacwlW365SR9HEiTnKEvJsHfJeMDGu5tRDdH+JhiboBDk9X9hC9rGXv1QQ2d39fxhyuc4oTeeK2X+gyQ/QKBkBJInUVVp7NBQls6rHMDfroPH6LIPCiP/d0MTC6GLN3eZeMDU6HeESClqcMpdo0q5gjdF6jUhAGDSwxPv1KelB8D27bLXJCGcXKezGx51A1no/UOccNboOFRs2C91kUBf+/U1or+2pzroPlEwUwtRzjFV9EE+5E2NFXXAoO5XlENvtn0Buklt7dXForTecp6AmiMr0kaddR3JuDsh9iNhUfvqluaLqTTo/+7RHlkMKheBhwdPa6/wR6VtNyVJoxVZ4rA3IzHfjcE3rxHB7Ow2PtZEXhlEhmEMy1IvbJiCZ9VSefn1uFR3gkmBES/S4o0o0z1oIkfftrTzicn9x6PkuBtO9aB/Femx4smcmU2uFNSoVr5jsdj3Fr5td5/V0E=
  - secure: EMlVmMFaZMVhcns2bh30ZLQEiQSFt46w/LCHWhDP9UTPR1YiIVjLhvpe/7sZIeyF5wiUg+vte97n++zl2QHFaBHijyJFocNl9ywMdkgXWWGNpskEWXk+BOfdjUPlcGniaJPwp5M/IvqrIGfCRALlcdIAlz3th09BpvUQcTuNxNZodc+Tl6M4Ow/XTU+TyymaD7ElZ37vTz4+ZaoPvZ4Q+2koaMuJm9ICipBfTSBzYIdMYkymggaIEW2TXZqN16TCqEUGyZktBYatf4rauE5sDGPE1C31WkRbJXJrqMu88CGqzExv+vYXRU6f/ncLOZWkLnM9b6f5ivOUpFrNPPQDC/ciScykRyZcsFzjzFqHGcne/No1kS8EDE13/tNzf6ZTQ3FA0cVnSQaTpZTPWCGz6/y/7rFFMNdi4KqS2eEcU1tg85jSdgjyKsSzYyJDGRaKV2RETz9hUHeBFQ1DHgJN0iaY+rrxybmez3FRNhtW8hbe8m/JdO3UevccLplCiKsxw642unn+NhJ8cfo6gxFeqir70uhnUtpmmDbxYXtvk9DbsTR5R9W5y8lm44q4kAezyIGT2ZucRmhDoM5FoE3gJ+kP8MAXyVk9SFeNfzhZSFIuRWJPm0WXISk4GRgKNz1Tm/jg2E19jWsKc9a5phuCGeziAhspT0NuvZrWCzq6IQw=
  - secure: RKzdwwIO7h5KcqjYfF7XedL80J/NlNeSoQ7PvtAcmXfJWGxEgBI7xg8h3ktmV6YphIA3BnKV0AgoHK4ZzKmUSkPh7XbmlT4diGGe8afH4TXK3OykCSmu5bYtNAWxgxWPAQCE2UlJUjTxv5Yh0y26lgM0PCdLpYJVsyd+0dCwxiyv+0+T1n086X/Ib4T0E/YwfwWJSm1JeUteML7hmsns8LvZQKdjQ2NCqOOdddSSW9V8v5zVPZm5UTyxMxeXvuLwOWz1fPbE+kNiLN6nvK8PW4pr5GWh+Y1e+/kREtk6T5394EfdZLYVOB5rXqGDOjURSTeGLMRVdCks5PBvktYueBnLtG8EzI/5hkD9nt9RvN7LmHYSdxMSgHh5Nl6JyfVUHBG/4FgV0XEoilrmt1CNs8v3mOA0wIR3SJo7MJkKSgj0Uvx0HlNbk2RmJAs9uRO9zE94oUz5Jpiy+U8l2s8iBSuIXNAVVePu9okyoSTbHmD6VEZO3Ym1gkMSWmEzNrfl7gUERX0DS14gUYQSvwlQlgyzKpIl01YqucC70qQ5zWXhF/w4ucy/4BeV2AtmptIrMaSI4DxQUoSVeAsteY0y0n5o0XOHZI67wjsCEl2r0UpDMOxAagGHgwpg/6JRy+zh25FLg4sAn9X8eUQa8UIKTY82ST52V03NEezCBOSZPdY=
