language: go
go:
  - "1.10"

script:
  - go build -o $TRAVIS_BUILD_DIR/bin/tokeninfo
  - mv $TRAVIS_BUILD_DIR/scripts/ $TRAVIS_BUILD_DIR/bin/
  - mv $TRAVIS_BUILD_DIR/appspec.yml $TRAVIS_BUILD_DIR/bin/
  - cd $TRAVIS_BUILD_DIR/bin
  - zip -r latest *
  - mkdir -p dsource
  - mv latest.zip dsource/latest.zip

deploy:
- provider: s3
  access_key_id: $AWS_ACCESS_KEY
  secret_access_key: $AWS_SECRET_KEY
  bucket: $S3_BUCKET
  region: $AWS_REGION
  skip_cleanup: true
  local_dir: dsource
  upload-dir: tokeninfo
- provider: codedeploy
  access_key_id: $AWS_ACCESS_KEY
  secret_access_key: $AWS_SECRET_KEY
  bucket: $S3_BUCKET
  region: $AWS_REGION
  key: tokeninfo/latest.zip
  bundle: zip
  application: tokeninfo-test-app
  deployment_group: tokeninfo-test-deployment-group

