language: go
go:
  - "1.10"

script:
  go build -o $TRAVIS_BUILD_DIR/bin/tokeninfo
  
deploy:
- provider: s3
  access_key_id: $AWS_ACCESS_KEY
  secret_access_key: $AWS_SECRET_KEY
  bucket: $S3_BUCKET
  region: $AWS_REGION
  skip_cleanup: true
  local_dir: bin
  upload-dir: tokeninfo
