version: 0.0

os: linux
files:
   - source: /
     destination: /opt/app/tokeninfo
permissions:
   - object: /opt/app/tokeninfo
     pattern: "**"
     owner: tokeninfo
     group: tokeninfo
     mode: 755
     type:
       - file
