version: 0.0

os: linux
files:
   - source: /
     destination: /opt/app/tokeninfo
permissions:
   - object: /opt/app/tokeninfo
     pattern: "**"
     owner: tokeninfo
     group: tokeninfo
     mode: 755
hooks:
  BeforeInstall:
    - location: hooks/before_install.sh
  ApplicationStart:
    - location: hooks/application_start.sh